catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedBooksListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdateView.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDeleteView.as_view(), name='author-delete'),
    path('book/create/', views.BookCreateView.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdateView.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDeleteView.as_view(), name='book-delete')
]

local_library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

catalog/models/author.py
from django.db.models import CharField, DateField, Model
from django.urls import reverse

class Author(Model):
    first_name = CharField(max_length=100)
    last_name = CharField(max_length=100)
    date_of_birth = DateField(null=True, blank=True)
    date_of_death = DateField('died', null=True, blank=True)

    def __str__(self) -> str:
        return f'{self.last_name}, {self.first_name}'

    def get_absolute_url(self) -> str:
        return reverse('author-detail', args=[str(self.id)])

    @property
    def age_range(self) -> str:
        if self.date_of_birth and self.date_of_death:
            return f'{self.date_of_birth} - {self.date_of_death}'
        elif self.date_of_birth:
            return f'{self.date_of_birth} - '
        elif self.date_of_death:
            return f' - {self.date_of_death}'
        else:
            return ''

    class Meta:
        ordering = ['last_name', 'first_name']

catalog/models/book.py
from django.db.models import (
    CharField,
    ForeignKey,
    ManyToManyField,
    Model,
    RESTRICT,
    SET_NULL,
    TextField
)
from django.urls import reverse

from .author import Author
from .genre import Genre
from .language import Language

class Book(Model):
    LANGUAGES = {
        'en': 'English',
        'fs': 'Farsi',
    }

    title = CharField(max_length=200)
    author = ForeignKey(Author, on_delete=RESTRICT, null=True)
    language = ForeignKey(Language, on_delete=SET_NULL, null=True)

    summary = TextField(
        max_length=1000,
        help_text='Enter a brief description of the book'
    )

    isbn = CharField(
        'ISBN',
        max_length=13,
        unique=True,
        help_text='13 Character ' \
            '<a href="https://www.isbn-international.org/content/what-isbn' \
            '">ISBN number</a>'
    )

    genre = ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self) -> str:
        return self.title

    def display_genre(self) -> str:
        """
        Create a string for the Genre.
        This is required to display genre in Admin.
        """
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self) -> str:
        return reverse('book-detail', args=[str(self.id)])

    class Meta:
        ordering = ['title']

catalog/models/bookinstance.py
from datetime import date
import uuid

from django.conf import settings
from django.db.models import (
    CharField,
    DateField,
    ForeignKey,
    Model,
    RESTRICT,
    SET_NULL,
    UUIDField
)

from .book import Book

class BookInstance(Model):
    LOAN_STATUS = {
        'm': 'Maintenance',
        'o': 'On loan',
        'a': 'Available',
        'r': 'Reserved'
    }

    id = UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text='Unique ID for this book across the whole library'
    )

    book = ForeignKey(Book, on_delete=RESTRICT, null=True)
    imprint = CharField(max_length=200)
    due_back = DateField(null=True, blank=True)

    status = CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability'
    )

    borrower = ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=SET_NULL,
        null=True,
        blank=True
    )

    def __str__(self) -> str:
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self) -> bool:
        return self.due_back and date.today() > self.due_back

    def display_book_title(self) -> str:
        return self.book.title

    display_book_title.short_description = 'Title'

    class Meta:
        ordering = ['due_back']
        permissions = (('can_mark_returned', 'Set book as returned'), )

catalog/models/genre.py
from django.db.models import CharField, Model, UniqueConstraint
from django.db.models.functions import Lower
from django.urls import reverse

class Genre(Model):
    name = CharField(
        max_length=200,
        unique=True,
        help_text='Enter a book genre ' \
            '(e.g. Science Fiction, French Poetry etc.)'
    )

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return reverse('genre-detail', args=[str(self.id)])

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='genre_name_case_insensitive_unique',
                violation_error_message='Genre already exists ' \
                    '(case-insensitive match)'
            )
        ]

catalog/models/language.py
from django.db.models import CharField, Model, UniqueConstraint
from django.db.models.functions import Lower
from django.urls import reverse

class Language(Model):
    name = CharField(
        max_length=200,
        unique=True,
        help_text="Enter the book's natural language " \
            "(eg: English, French, Japanese etc.)"
    )

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return reverse('language-detail', args=[str(self.id)])

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='language_name_case_insensitive_unique',
                violation_error_message='Language already exists ' \
                    '(case-insensitive match)'
            )
        ]

catalog/forms.py
import datetime

from django.core.exceptions import ValidationError
from django.forms import CharField, DateField, Form, ModelForm
from django.utils.translation import gettext_lazy as _

from .models import BookInstance

class RenewBookForm(Form):
    renewal_date = DateField(
        help_text='Enter a date between now and 4 weeks (default 3).',
        label='Renewal date',
    )

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(
                _('Invalid date - renewal in the past'),
                code='invalid_date'
            )

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'),
                code='invalid_date'
            )

        return data

class RenewBookModelForm(ModelForm):
    virtual_field = CharField(max_length=200)

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise ValidationError(
                _('Invalid date - renewal in the past'),
                code='invalid_date'
            )

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'),
                code='invalid_date'
            )

        return data

    def clean_virtual_field(self):
        # Custom validation for the virtual field
        data = self.cleaned_data['virtual_field']
        # Add your validation logic here
        return data

    class Meta:
        model = BookInstance
        fields = ('due_back', 'virtual_field')
        labels = {'due_back': _('New renewal date')}

        help_texts = {
            'due_back': _('Enter a date between now and 4 weeks (default 3).')
        }

catalog/forms/renewbookform.py
import datetime

from django.core.exceptions import ValidationError
from django.forms import DateField, Form
from django.utils.translation import gettext_lazy as _

class RenewBookForm(Form):
    renewal_date = DateField(
        help_text='Enter a date between now and 4 weeks (default 3).',
        label='renewal date',
    )

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(
                _('Invalid date - renewal in the past'),
                code='invalid_date'
            )

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'),
                code='invalid_date'
            )

        return data

catalog/forms/renewbookmodelform.py
import datetime

from django.core.exceptions import ValidationError
from django.forms import CharField, ModelForm
from django.utils.translation import gettext_lazy as _

from ..models import BookInstance

class RenewBookModelForm(ModelForm):
    virtual_field = CharField(max_length=200)

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise ValidationError(
                _('Invalid date - renewal in the past'),
                code='invalid_date'
            )

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'),
                code='invalid_date'
            )

        return data

    def clean_virtual_field(self):
        # Custom validation for the virtual field
        data = self.cleaned_data['virtual_field']
        # Add your validation logic here
        return data

    class Meta:
        model = BookInstance
        fields = ('due_back', 'virtual_field')
        labels = {'due_back': _('New renewal date')}

        help_texts = {
            'due_back': _('Enter a date between now and 4 weeks (default 3).')
        }

catalog/views/authorcreateview.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView

from ..models import Author

class AuthorCreateView(PermissionRequiredMixin, CreateView):
    model = Author
    fields = ('last_name', 'first_name', 'date_of_birth', 'date_of_death')
    # initial = {'date_of_death': '11/11/2023'}
    permission_required = 'catalog.add_author'

catalog/views/authordeleteview.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import DeleteView

from ..models import Author

class AuthorDeleteView(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.delete_author'

    def form_valid(self, _):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception as error:
            return HttpResponseRedirect(reverse(
                'author-delete',
                kwargs={'pk': self.object.pk}
            ))

catalog/views/authordetailview.py
from django.views.generic import DetailView

from ..models import Author

class AuthorDetailView(DetailView):
    model = Author

catalog/views/authorlistview.py
from django.views.generic import ListView

from ..models import Author

class AuthorListView(ListView):
    model = Author
    paginate_by = 10

catalog/views/authorupdateview.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import UpdateView

from ..models import Author

class AuthorUpdateView(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ('last_name', 'first_name', 'date_of_birth', 'date_of_death')
    permission_required = 'catalog.change_author'

catalog/views/bookcreateview.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView

from ..models import Book

class BookCreateView(PermissionRequiredMixin, CreateView):
    model = Book
    fields = ('title', 'author', 'summary', 'isbn', 'genre', 'language')
    permission_required = 'catalog.add_book'

catalog/views/bookdeleteview.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import DeleteView

from ..models import Book

class BookDeleteView(PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'catalog.delete_book'

    def form_valid(self, _):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception as error:
            return HttpResponseRedirect(reverse(
                'book-delete',
                kwargs={'pk': self.object.pk}
            ))

catalog/views/bookdetailview.py
from django.views.generic import DetailView

from ..models import Book

class BookDetailView(DetailView):
    model = Book

catalog/views/booklistview.py
from django.views.generic import ListView

from ..models import Book

class BookListView(ListView):
    model = Book
    paginate_by = 10

    # def get_context_data(self, **kwargs) -> dict[str, Any]:
    #     context = super().get_context_data(**kwargs)
    #     context['some_data'] = 'This is just some data'
    #     return context

    # def get_queryset(self):
    #     return Book.objects.all()

catalog/views/bookupdateview.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import UpdateView

from ..models import Book

class BookUpdateView(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = ('title', 'author', 'summary', 'isbn', 'genre', 'language')
    permission_required = 'catalog.change_book'

catalog/views/borrowedbookslistview.py
from typing import Any
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models.query import QuerySet
from django.views.generic import ListView

from ..models import BookInstance

class BorrowedBooksListView(PermissionRequiredMixin, ListView):
    model = BookInstance
    paginate_by = 10
    permission_required = ('catalog.can_mark_returned')
    template_name = 'catalog/bookinstance_list_borrowed.html'

    def get_queryset(self) -> QuerySet[Any]:
        return (BookInstance.objects
            .filter(status__exact='o')
            .order_by('due_back'))

catalog/views/loanedbooksbyuserlistview.py
from typing import Any
from django.contrib.auth.mixins import (LoginRequiredMixin)
from django.db.models.query import QuerySet
from django.views.generic import ListView

from ..models import BookInstance

class LoanedBooksByUserListView(LoginRequiredMixin, ListView):
    model = BookInstance
    paginate_by = 10
    template_name = 'catalog/bookinstance_list_borrowed_user.html'

    def get_queryset(self) -> QuerySet[Any]:
        return (BookInstance.objects
            .filter(borrower=self.request.user, status__exact='o')
            .order_by('due_back'))

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author: {{ author }}</h1>

{% if author.book_set.all %}

<p>You can't delete this author until all their books have been deleted:</p>
<ul>
  {% for book in author.book_set.all %}
    <li><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</li>
  {% endfor %}
</ul>

{% else %}
<p>Are you sure you want to delete the author?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
{% endif %}

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author }}</h1>
  <p><small>{{ author.age_range }}</small></p>

  <h2>Books</h2>

  {% for copy in author.book_set.all %}
    <div>
      <h3><a href="{{ copy.get_absolute_url }}">{{ copy.title }}</a></h3>
      <p>{{ copy.summary }}</p>
    </div>
  {% empty %}
    <p>No books added</p>
  {% endfor %}
{% endblock %}

{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_author or perms.catalog.delete_author %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_author %}
      <li><a href="{% url 'author-update' author.id %}">Update author</a></li>
    {% endif %}
    {% if not author.book_set.all and perms.catalog.delete_author %}
      <li><a href="{% url 'author-delete' author.id %}">Delete author</a></li>
    {% endif %}
    </ul>
  {% endif %}
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>

  {% if author_list %}
    <ul>
      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author }}</a>
        {% if author.age_range %}({{ author.age_range }}){% endif %}
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no authors in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author: {{ author }}</h1>

{% if author.book_set.all %}

<p>You can't delete this author until all their books have been deleted:</p>
<ul>
  {% for book in author.book_set.all %}
    <li><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</li>
  {% endfor %}
</ul>

{% else %}
<p>Are you sure you want to delete the author?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
{% endif %}

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr />
      <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_book or perms.catalog.delete_book %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_book %}
      <li><a href="{% url 'book-update' book.id %}">Update book</a></li>
    {% endif %}
    {% if not book.book_instance.all and perms.catalog.delete_book %}
      <li><a href="{% url 'book-delete' book.id %}">Delete book</a></li>
    {% endif %}
    </ul>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>

  {% if book_list %}
    <ul>
      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
        ({{book.author}})
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p {% if book_instance.is_overdue %} class="text-danger"{% endif %} >Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
        {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>{% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}